### ISSUE TITLE
Dynamic Partials and Partial Collections through Coercion

### ISSUE THREAD

**Issue by thelucid** [mustache/spec#54]
I've just created a pull request over at https://github.com/janl/mustache.js/pull/242

I am using this solution in a couple of projects and it addresses a number of concerns I often hear with regards dynamic partials in Mustache, please see ticket (https://github.com/janl/mustache.js/pull/242) and documentation here:
- https://github.com/thelucid/mustache.js#dynamic-partials
- https://github.com/thelucid/mustache.js#partial-collections

Really, I urge everyone to have a play with it as it has cleaned up my templates no end.

Kind regards,

Jamie

**Comment by spiffytech** [comment]
*bump*

Any movement on a v2 spec that includes this feature?

**Comment by hydrastro** [comment]
> _bump_
> 
> Any movement on a v2 spec that includes this feature?

^

**Comment by jgonggrijp** [comment]
To anyone still hoping for a feature that involves detecting a hard-coded name such as `partial` in the context: I don't see that ever happening. Not that I'm the one to decide, but I think too many people are against it (for reasons that I agree with).

To anyone still looking for a way to dynamically select a partial based on context, I suggest the following approach based on feature detection.

Data:

```js
{
  items: [
    { content: 'Some text' },
    { url: 'Some URL' }
  ]
}
```

Templates:

```mustache
{{!base.mustache}}
{{#items}}
<p>{{>polymorphic}}</p>
{{^items}}

{{!polymorphic.mustache}}
{{#content}}
    {{>text}}
{{/content}}
{{#url}}
    {{>image}}
{{/url}}

{{!text.mustache}}
{{content}}

{{!image.mustache}}
<img src="{{url}}"/>
```

I know, I know. This looks suspiciously like the code that @thelucid was trying to avoid. The `base` template is not dynamically selecting a partial at all, to the contrary. It's expanding the same one every time, `polymorphic`, and that just contains the if-else again that @thelucid wanted to get rid of. You might think that I just moved the problem. **But** consider the following.

- `polymorphic.mustache` *is performing dynamic partial selection*. And nothing else. So we have a clean separation of concerns.
- `base.mustache` no longer contains the if-else; it is as clean as the "fine-grained control" version of what @thelucid was suggesting.
- With this approach, *you don't need to tag your data in any way*. No hard-coded `partial` property that names a partial, no `html` property with a lambda. Just the actual data.
- By extension, the code that prepares the data no longer needs to contain an if-else construction for injecting the tags. So I have actually **moved the solution**. Arguably to a better place, since Mustache templates are portable while your data-preparing code is not.

Last but not least: this already works, even without the lamdas extension, so you don't need to wait for anyone to change a specification in highly controversial ways.

**Comment by anomal00us** [comment]
> * `polymorphic.mustache` _is performing dynamic partial selection_. And nothing else. So we have a clean separation of concerns.
Yes, it is performing dynamic partial selection, but it's not an ideal solution for all cases: in your example your dynamic loading is bounded to your data structure / template, which is fairly limited

In my template I want to dynamically load contents of a page, following your example this is what my code would look like:
```
{{!template.mustache}}
{{>header}}
{{>content}}
{{>footer}}

{{!content.mustache}}
{{#mainpage}}
  {{>mainpage}}
{{/mainpage}}
{{#aboutpage}}
  {{>aboutpage}}
{{/aboutpage}}
{{#foobarpage}}
  {{>foobarpage}}
{{/foobarpage}}
{{!and so on... for all my pages in the database}}
```
I could use lambdas to solve this but I find it kinda tedious (not to mention the fact that this way I'm still tagging the data).  
(Also I have no idea how to do it).
Or I could dynamically generate templates with a wrapper language  
Wrapper:
```php
<?php
$content_file = "foobar.mustache";
ob_start();
include("template.mustache.php");
$content = ob_get_clean();
// (mustache rendering here)
?>
```
template.mustache.php:
```php
{{>header}}
{{><?=$content_file;?>}}
{{>footer}}
```
Pretty bad right?

>you don't need to wait for anyone to change a specification in highly controversial ways.  

We don't want to change a specification, we just want to add a feature, a new token.  
Here's the proposal:  
Data:
```{
  content: "mainpage"
}```
Templates:
```
{{!template.mustache}}
{{>header}}
{{*content}}
{{>footer}}
```
Pretty simple, right?  
This would make life easier for a lot of people.   
PS. I didn't know which operator to choose, so I just picked up `*`, we can change it.

**Comment by gasche** [comment]
I'm new to this discussion and the top post has mostly dead links. Can proponents of the change point to a post that clearly explains the feature being proposed?

I have the impression that some use-cases are in common with "template inheritance" which was finally accepted as an optionally-supported feature (see https://github.com/mustache/spec/pull/125):

base.mustache:
```
header...
{{ $content }}
footer...
```

main.mustache:
```
{{< base }}{{$content}}
main page content...
{{/content}}{{/base}} 
```

aboutpage.mustache:
```
{{< base }}{{$content}}
about page content...
{{/content}}{{/base}} 
```

(This can be extended to pass a title to the base template, etc.)

**Comment by anomal00us** [comment]
> some use-cases are in common with "template inheritance" which was finally accepted as an optionally-supported feature (see #125)

Yes, you're right, some use cases are common.  
What we're proposing is to solve the problem the other way,  "forward" (with "includes"/dynamic partials) rather than "backwards" (with inheritance).  
It's way more clean. 

Data:
```
{
  content: "aboutpage"
}
```
Templates:
```
{{!base.mustache}}
{{>header}}
{{*content}}
{{>footer}}

{{!main.mustache}}
main page content...

{{!aboutpage.mustache}}
about page content...
```

**Comment by jgonggrijp** [comment]
@gasche The originally proposed feature is described in detail in https://github.com/janl/mustache.js/pull/242.

@anomal00us You are proposing a different feature, although it serves the same purpose and the suggested syntax may have been inspired on the discussion. To be honest, I find your proposal more sensible than the original. The syntax is less surprising and it doesn't involve a hard-coded special name.

I must point out that this is the spec repository. If you only want to add a feature to one particular implementation, you should probably take the discussion to that implementation. There is nothing wrong with discussing it here (again, as I said, I actually like what you're describing), but anything discussed here is about changing the specification, by definition.

**Comment by jgonggrijp** [comment]
Following up on what I just wrote: I realized that the syntax `{{*key}}` could theoretically be generalized to also supporting similar constructions with parents or even sections. This is why the discussion contained more radical suggestions such as `{{> &key}}` and `{{> "name"}}`. I pondered for a moment whether dynamic parents should be possible, and if so, how.

I ended up deciding that I like the language more in the minimalist form that it has today. As far as I'm concerned, there is still room for dynamic partials with a `{{*key}}` syntax, but we shouldn't take the dereferencing any further than that. There doesn't need to be a dynamic parent for parity, because as @anomal00us pointed out, inheritance and dynamic partials are to some extent alternatives. I certainly wouldn't want to complicate the internals of tags in order to support key dereferencing more generally.

**Comment by anomal00us** [comment]
> I must point out that this is the spec repository. If you only want to add a feature to one particular implementation, you should probably take the discussion to that implementation.

Yes, I know. I already added this into my implementation, that's also why I am here.
It would be cool if this will be merged into the spec!

> I realized that the syntax `{{*key}}` could theoretically be generalized to also supporting similar constructions with parents or even sections.

Can you make an example?
Do you mean something like this: (?)
Data:
```
{
  items: [
    { content: 'header' },
    { content: 'mainpage' },
    { content: 'footer' },
  ]
}
```
Template:
```
{{!template.mustache}}
{{#items}}{{*content}}{{/items}}
```


> but we shouldn't take the dereferencing any further than that.

I totally agree.

>There doesn't need to be a dynamic parent for parity, because as @anomal00us pointed out, inheritance and dynamic partials are to some extent alternatives. I certainly wouldn't want to complicate the internals of tags in order to support key dereferencing more generally.

So if we're writing a pull request for this we're going to keep things simple and allow deferencing only on simple data?

**Comment by anomal00us** [comment]
> Can you make an example?

Ah I think I got it. Making * a deference operator and allowing to combine it with all the other tags, right?  
```
{{#*deferencedarray}}
  {{&*deferencedunescaped}}
{{/*deferencedarray}}
{{**doubledeference}}
{{<*deferencedparent}}
```
Well, I don't feel like this is a good idea.. it's probably better to keep things simple.  
I may be wrong but I can't come up with ideas where you could possibly need to deference a section.  
Also implementing this would imply to change a lot of things, first of all the tokenizer, which will need to detect the * operator, then the abstract syntax tree generated by the parsers: we need an extra field to tell whether something is deferenced or not, and at last the compiler, which will need to "deference" the stuff.
Not to mention all the existing specifications.

So yeah, my proposal is to have `*` as dynamic partial only (stand alone) operator.

**Comment by jgonggrijp** [comment]
@anomal00us 

> So if we're writing a pull request for this we're going to keep things simple and allow deferencing only on simple data?

Honestly, *I* am probably not going to write a pull request for this, at least not soon, because I haven't implemented the feature myself (yet). But if *you* were to write one, I would definitely be in favor of keeping it simple, allowing only single-level dereferencing specifically for the purpose of interpolating plain partials (i.e., not parents). Basically, `{{*key}}` being a composition of `{{key}}` and `{{>value}}`. Also, I would be happy to review it.

**Comment by anomal00us** [comment]
Great, I'm planning to write it soon.

@jgonggrijp  do you know if there is a tool for getting the json from the yml, or did people here write everything by hand?

**Comment by anomal00us** [comment]
Okay I made PR #134

**Comment by jgonggrijp** [comment]
@anomal00us There is a command for it, which is mentioned in the Readme if I'm right. I suppose you already found it.

**Comment by bobthecow** [comment]
Probably a bad idea, but what if we spec general purpose dereferencing instead?

```mustache
{{*variable}}
{{#*list}}
{{>*template}}
{{/*list}}
```

```js
{
  variable: "a",
  list: "b",
  template: "c",
  a: "foo",
  b: [
    {name: "bar"},
    {name: "baz"},
  ],
  c: "somepartial"
}
```

```mustache
{{!somepartial.mustache}}
{{name}}
```

**Comment by jgonggrijp** [comment]
@bobthecow 

> Probably a bad idea, but what if we spec general purpose dereferencing instead?

It crossed other people's minds before, so at least it's not *stupid*. It was first discussed in 2012, from https://github.com/mustache/spec/issues/54#issuecomment-8679169 onwards. That never led to anything (at least not in the spec). It was again discussed by me and @anomal00us just a few days ago, from https://github.com/mustache/spec/issues/54#issuecomment-985633165 onwards. Bottom line of the latter discussion is that we both preferred not complicating the tag contents. See also #134.

For me personally, Mustache's syntactic simplicity is one of its main selling points. A general purpose dereference operator would arguably make the language even more powerful than it already is, but I think the added value is questionable for all tags except partials (where it enables a template equivalent of polymorphism through tagged unions, similar to how parents and blocks enable polymorphism through inheritance). I feel it would also start a slippery slope towards a bloated language like Handlebars or Jinja. Besides dereferencing, can we apply other general purpose operators within tag contents? Can we dereference multiple levels? Etcetera... it's a direction I rather not explore.

On another note, I would be highly interested in your opinion on #131.

**Comment by bobthecow** [comment]
ahahahahah i clicked through from #134 and didn't expand all the collapsed past conversation here and missed that I proposed this exact thing a decade ago when it first came up 😛 

https://github.com/mustache/spec/issues/54#issuecomment-8674827

**Comment by bobthecow** [comment]
The question of dynamic tag names has come up for more than just partials in the past. To me it feels far more consistent to add a general purpose dereference operator (while I do acknowledge the slope we start slipping down) than to introduce a special form of partial that pulls the template name from the view model.

**Comment by jgonggrijp** [comment]
My question is this: can't we make a hard choice to not start slipping down that slope? We could have dereferencing in other ways. For example, we could give lambdas (read-only) access to the context stack through an additional argument.

**Comment by agentgt** [comment]
I agree with @bobthecow a general purpose dereference operator might be useful when trying to reference things that would normal iterate or be conditional especially in the context of #135 .

That is the only need of dereferencing in my implementation since we don't support dynamic partials (or templates in general) is to pass lists and booleans around to lambdas.

Currently the easiest solution for my case is to use virtual keys instead of a new sigil. e.g. to reference a list instead of iterating I do the following:

```
{{#someList.this}}
{{#someLambdaExpectsListOnTopOfStack}}
{{/someLambdaExpectsListOnTopOfStack}}
{{/someList.this}}
```

`this` being the special virtual key that would kind of be equivalent to `{{#*someList}}`.

I am starting to get the idea that a large amount of problems that should be easy in mustache can be solved with virtual keys notable index information (e.g. `-last`, `@last` a boolean virtual binding that indicates if you are on the last item in a list).

Virtual keys are much easier to add to existing implementations than a new sigil albeit I'm not sure if that holds up to dynamic partial needs (to be frank I'm like @gasche in that I'm not sure if I even follow all the ideas in this thread).

**Comment by jgonggrijp** [comment]
@agentgt In my particular implementation, adding virtual keys like `@last` would actually be much harder than adding new sigils. That's because my tokenizer and parser already have generic facilities for sigils, but there is nothing yet to handle special reserved key names (other than the entire key being the implicit iterator `.`).

Power lambdas would make it possible to add your own virtual keys, but we already discussed that in #135. I understand it doesn't help in your case, and I figure that your implementation probably does already inspect key names inside the template, since it aims to typecheck everything. Mustache was clearly conceived as a dynamically typed language.

For context, dynamic partials did make it into the spec eventually, in #134.
