### ISSUE TITLE
Feature Request: Inline partials

### ISSUE THREAD

**Issue by spudly** [mustache/spec#63]
Partials are great, but it'd sure be nice to be able to define partials right inside the template that uses them. In most cases, the partials I create are only used by one parent template so it's a lot of extra work to create the partial the way it works right now. Also, a lot of my partials are one-liners. As a result, I often times end up just copy/pasting instead. It sure would be nice if we could define partials inline. See issue #59. This would allow us to write mini-templates that can be reused within the same template. Here's some possible syntax:

Definition:

``` html
{{*mypartial}}
    <li title='{{title}}'>{{text}}</li>
{{/}}
```

Usage:

``` html
<ul>
  {{#items}}
    {{**mypartial}}
  {{/items}}
</ul>
```

**Comment by jgonggrijp** [comment]
For what it's worth, I like the following syntax for defining an inline partial most, which I copied nearly verbatim from @groue in https://github.com/mustache/spec/issues/63#issuecomment-12392147:

```mustache
{{=person}}
    <a href=...
{{/person}}

{{#democrats}}
    {{>person}}
{{/democrats}}
```

The only change I made is that I repeated the `person` name in the End Section tag. I believe that would be better for consistency.

I also like @groue's argument for using the `=` sigil: it looks like a definition. Although `:` would probably work as well, for the same reason.

Some considerations:

- This could be another optional extension, so it could be included in a 1.x release.
- Implementations that implement both inline partials and inheritance, ideally should also allow combining them. That is, the inline partial definition might contain Block tags and it may be expanded with Parent tags in order to override those blocks.
- The inline partial definition as a whole should probably be considered standalone, so it doesn't leave blank lines after rendering. Indentation *could* be handled in the same way as I'm proposing for Block and Parent tags in #131 and #130.
- In order to not overcomplicate things, I suggest allowing each inline partial to have only a single definition. @groue suggested a "last definition wins" approach, but this feels a bit too stateful to my taste. What happens when users break the single definition rule can be left implementation-defined.
- Also in order not to overcomplicate things, I suggest that inline partials can only be defined at the top scope of the template (so not inside sections, blocks, parents, etcetera). Again, it can be left implementation-defined what happens otherwise. (Note also that it can still be the other way round, e.g. a block appearing inside an inline partial. I can even imagine this being very useful.)
- I suggest that in case of name conflicts, inline partials take precedence over external partials. If the author of the template with the inline partial is unaware of the external partial, then she obviously expects the inline partial to be expanded. If she is aware of the external partial, then she always has the option to rename the inline partial in case she wants to be able to use both.

**Comment by jgonggrijp** [comment]
Following up on my previous comment: I just realized that the `=` sigil is already taken by the Change Delimiters tag. In that case I guess `:` remains as a "next best".

```mustache
{{:person}}
    <a href=...
{{/person}}

{{#democrats}}
    {{>person}}
{{/democrats}}
```

**Comment by lijiaqigreat** [comment]
Any updates? I need this feature for my project. Here is the use case:
I'm using mustache to write color theme for multiple apps. It's much easier to encapsulate one color theme in one template file, but for some color theme, it has a lot of repeated parts that can be eliminated by inline partials. ([example](https://github.com/SultanSGillani/dotfiles/blob/438d2a3ce8c2cb44c33502511bc5a0fa78a47d8e/roles/iterm/templates/iterm2.plist.j2))

**Comment by gasche** [comment]
> Implementations that implement both inline partials and inheritance, ideally should also allow combining them.

I agree, I see exactly the same use-cases with inheritance partials / parent tag.
Should the definition say whether it is defining a closed partial (no block parameter) or a parent tag? (eg `{{:>name}}` vs. `{{:<name}}`.) Or do we consider that they live in the same namespace, as for external partials/parents? The latter sounds simpler.

> In order to not overcomplicate things, I suggest allowing each inline partial to have only a single definition. @groue suggested a "last definition wins" approach, but this feels a bit too stateful to my taste.
> [...]
> I suggest that in case of name conflicts, inline partials take precedence over external partials.

@jgonggrijp There is a small contradiction between your two proposals here, you want to avoid definition-precedence rules for inline partials, but still define precedence rules between inline partials and external partials.

I think that your internal-vs-external conforms to the general intuition of "the nearest definition wins" (as in, say, the CSS cascade model): internal definitions are closer to the use-case so they take precedence. It should be possible to have a similar notion of lexical scope for internal definitions, and that would tell us what is the right behavior in presence of multiple declarations.

To reformulate: what is the "visibility" of a partial/parent definition?
- the whole file, including what's before it in the file?
- or maybe just what follows? (sounds nicer)
- if we allow definitions inside sections, do they remain visible after the section end? (does not sound like a good idea)
- if we use a partial after the definition, is the definition visible from within the partial? (it sounds like a bad idea to me)

> Also in order not to overcomplicate things, I suggest that inline partials can only be defined at the top scope of the template

This is a simplification, but it's also a bit frustrating because it is nice/appealing/convenient to be allowed to define inline partials close to their use-sites, which may be at the end of a long section for example.

```
{{#long-section}}
  lots of stuff
  {{:foo}}
  {{#list1}}{{>foo}}{{/list1}}
  {{#list2}}{{>foo}}{{/list2}}
{{/long-section}}
```

On the other hand, there is something we must be careful about: because the syntax for parent tag does not explicitly list its paremeters (unlike, say, a lambda-function syntax in most programming languages), there is a risk of ambiguity if we define an inline parent within an inline parent:

```
{{:<outer-parent-tag}}
  {{$arg}}{{/arg}}
  {{:<inner-parent-tag}}
    {{$other-arg}}{{/other-arg}}
  {{/inner-parent-tag]]
  ... uses {{<inner-parent-tag}} ...
{{/outer-parent-tag}}
```

in this example, is `other-arg` a block parameter of `inner-parent-tag` or of `outer-parent-tag`?

I think the best solution in this case is to say that `other-tag` is an argument of the innermost inline definition, because in the case where we really wanted to render a second argument of `outer-parent-tag` there is an ugly workaround:

```
{{:<outer-parent-tag}}
  {{$arg}}{{/arg}}
  {{:>ugly-workaround}}
    # render the argument here
    {{$other-arg}}{{/other-arg}}
  {{/ugly-workaround}}
  {{:<inner-parent-tag}}
    {{>ugly-workaround}}
  {{/inner-parent-tag]]
  ... uses {{<inner-parent-tag}} ...
{{/outer-parent-tag}}
```

Note: in this example I had to explicitly mark which inline definitions correspond to closed partials and which correspond to parent tags, because otherwise it would quickly get fairly confusing:


```
{{:outer-parent-tag}}
  {{$arg}}{{/arg}}
  {{:ugly-workaround}}
    # render the argument here
    {{$other-arg}}{{/other-arg}}
  {{/ugly-workaround}}
  {{:inner-parent-tag}}
    {{>ugly-workaround}}
  {{/inner-parent-tag]]
  ... uses {{<inner-parent-tag}} ...
{{/outer-parent-tag}}
```

The fact that parent-inside-parent is a bit delicate while closed-inside-parent is not suggests that it's good to force people to be explicit about whether they are defining an inline parent or an inline closed partial.

**Comment by jgonggrijp** [comment]
@lijiaqigreat 

> Any updates? I need this feature for my project.

This project, and the present discussion, is about writing a specification for the template language feature; it is not about *implementing* the feature. If this feature becomes part of the specification, that will not immediately help you, because you need an actual implementation.

> Here is the use case:
> I'm using mustache to write color theme for multiple apps. It's much easier to encapsulate one color theme in one template file, but for some color theme, it has a lot of repeated parts that can be eliminated by inline partials. ([example](https://github.com/SultanSGillani/dotfiles/blob/438d2a3ce8c2cb44c33502511bc5a0fa78a47d8e/roles/iterm/templates/iterm2.plist.j2))

It appears you are already using a Mustache implementation. I see some non-standard syntax, so maybe it already implements inline partials? Otherwise, you can use "regular" external partials; they provide all the same features, except that you have to define the partial in a separate template file instead of in the main template.

**Comment by jgonggrijp** [comment]
> I agree, I see exactly the same use-cases with inheritance partials / parent tag. Should the definition say whether it is defining a closed partial (no block parameter) or a parent tag? (eg `{{:>name}}` vs. `{{:<name}}`.) Or do we consider that they live in the same namespace, as for external partials/parents? The latter sounds simpler.

Yes, I would prefer the latter. According to the current spec, parents are *exactly* like partials, *except* that you can pass argument blocks (which necessitates the block end tag). External templates that are used as "plain" partials can still contain blocks, and external templates that don't contain any blocks can still be used as parents.

It would not only be the simplest, but also the most consistent, to apply the same rule to inline partials/parents. In fact, it is probably a bit of misnomer to call them inline "partials" or "parents"; we should call them inline *templates* instead (or maybe "inline subtemplates", or "nested templates", to emphasize the nesting relationship). Whether another template is interpolated as a partial or a parent is decided at the site of interpolation, not at the site of definition.

> 
> > In order to not overcomplicate things, I suggest allowing each inline partial to have only a single definition. @groue suggested a "last definition wins" approach, but this feels a bit too stateful to my taste.
> > [...]
> > I suggest that in case of name conflicts, inline partials take precedence over external partials.
> 
> @jgonggrijp There is a small contradiction between your two proposals here, you want to avoid definition-precedence rules for inline partials, but still define precedence rules between inline partials and external partials.
> 
> I think that your internal-vs-external conforms to the general intuition of "the nearest definition wins" (as in, say, the CSS cascade model): internal definitions are closer to the use-case so they take precedence. It should be possible to have a similar notion of lexical scope for internal definitions, and that would tell us what is the right behavior in presence of multiple declarations.

I meant something else: I do not want to specify what should happen when multiple inline tempate definitions have the same name, because doing that just is not clean, can easily be avoided and should not be encouraged. I think that inline templates ideally also should not have the same name as pre-existing external templates, but since that is harder to avoid, specifying the precedence still seemed necessary. Note that the spec does not specifiy what to do when multiple external templates have the same name, either.

I agree that "innermost wins" is a good rule in general. However, I believe there is no added value in allowing inline templates to "shadow" other inline templates. The template author is in full control of the template file, so if she wants to alternate between different versions of an inline template, she can just use different names. I should add that I am trying to keep my [implementation](https://gitlab.com/jgonggrijp/wontache/-/blob/integration/mustache/mustache.coffee) as small as possible, and inline template names being tied to particular scopes (or being redefined at text order like Change Delimiter) is not going to help with that mission.

> 
> To reformulate: what is the "visibility" of a partial/parent definition?
> 
> * the whole file, including what's before it in the file?
> * or maybe just what follows? (sounds nicer)

I would prefer the first option. Having to enforce that the inline template is invisible before the point of definition would significantly complicate my implementation.

Some users will prefer to put all their inline templates at the top (bottom-up programmers), while others might want to put all of them at the bottom (top-down programmers). I don't think either order is inherently better than the other.

On the other hand, the bottom-up order (definition before use) is probably a bit more consistent with Change Delimiter. We could also specifiy that the template must be visible after the definition, but leave it to the implementation to decide whether it is also visible before the definition.

On the *other* other hand, external templates are unordered, so there is something to say for inline templates to be unordered as well. That would again speak in favor of them being visible throughout the containing template file.

> * if we allow definitions inside sections, do they remain visible after the section end? (does not sound like a good idea)

Again, I would prefer not to tie the inline template to a particular scope, in order to keep the implementation compact.

> * if we use a partial after the definition, is the definition visible from within the partial? (it sounds like a bad idea to me)

External templates can be recursive, so I think it would be most consistent if inline templates can be, too. It also seems easiest to implement, since inline templates can be made of exactly the same "stuff" as external templates in that case.

> 
> > Also in order not to overcomplicate things, I suggest that inline partials can only be defined at the top scope of the template
> 
> This is a simplification, but it's also a bit frustrating because it is nice/appealing/convenient to be allowed to define inline partials close to their use-sites, which may be at the end of a long section for example.
> 
> ```
> {{#long-section}}
>   lots of stuff
>   {{:foo}}
>   {{#list1}}{{>foo}}{{/list1}}
>   {{#list2}}{{>foo}}{{/list2}}
> {{/long-section}}
> ```

Granted. I am not necessarily opposed to allowing the definition to appear within a nested scope, but in that case I would still want to "hoist" the inline template to the top scope, for the reasons I already discussed above.

> 
> On the other hand, there is something we must be careful about: because the syntax for parent tag does not explicitly list its paremeters (unlike, say, a lambda-function syntax in most programming languages), there is a risk of ambiguity if we define an inline parent within an inline parent:
> 
> ```
> {{:<outer-parent-tag}}
>   {{$arg}}{{/arg}}
>   {{:<inner-parent-tag}}
>     {{$other-arg}}{{/other-arg}}
>   {{/inner-parent-tag]]
>   ... uses {{<inner-parent-tag}} ...
> {{/outer-parent-tag}}
> ```
> 
> in this example, is `other-arg` a block parameter of `inner-parent-tag` or of `outer-parent-tag`?

I think this is a non-issue. Reading the spec closely (and figuring out how to pass it 100%), I found that any argument blocks provided to a template from the outside must be passed implicitly to any nested parents:

https://github.com/mustache/spec/blob/b2aeb3c283de931a7004b5f7a2cb394b89382369/specs/%7Einheritance.yml#L182-L209

The outer template can also explicitly pass the block to the inner template, in which case the point becomes moot entirely:

```
{{:<outer-parent-tag}}
  {{$arg}}{{/arg}}
  {{:<inner-parent-tag}}
    {{$other-arg}}{{/other-arg}}
  {{/inner-parent-tag]]
  ... {{<inner-parent-tag}}{{$other-arg}}{{/other-arg}}{{/inner-parent-tag}} ...
{{/outer-parent-tag}}
```

Why on earth should inline subtemplates have their own inline sub-subtemplates in the first place, though? That, again, seems needlessly complicated to me. This could be another reason to allow them only at top scope, as I suggested before, or alternatively, just to disallow nesting them. I will demonstrate below why nesting inline templates adds no value.

> 
> I think the best solution in this case is to say that `other-tag` is an argument of the innermost inline definition,

I agree to this purely because of consistency. `other-arg` appears inside `inner-parent-tag`, so the former is a parameter of the latter.

> because in the case where we really wanted to render a second argument of `outer-parent-tag` there is an ugly workaround:
> 
> ```
> {{:<outer-parent-tag}}
>   {{$arg}}{{/arg}}
>   {{:>ugly-workaround}}
>     # render the argument here
>     {{$other-arg}}{{/other-arg}}
>   {{/ugly-workaround}}
>   {{:<inner-parent-tag}}
>     {{>ugly-workaround}}
>   {{/inner-parent-tag]]
>   ... uses {{<inner-parent-tag}} ...
> {{/outer-parent-tag}}
> ```

I don't think that workaround should be necessary. The spec for inheritance in external templates allows multiple templates to have block parameters with the same name, so the same should be allowed for inline templates, as far as I'm concerned.

```
{{:<outer-parent-tag}}
    {{$arg}}{{/arg}}
    {{:<inner-parent-tag}}
        {{$other-arg}}{{/other-arg}}
    {{/inner-parent-tag}}
    {{<inner-parent-tag}}
        {{$other-arg}}{{/other-arg}}
    {{/inner-parent-tag}}
    {{! optionally, let us use the second argument in the outer inline template as well}}
    {{$other-arg}}{{/other-arg}}
{{/outer-parent-tag}}
```

The above template will have exactly the same semantics if we deforest it:

```
{{:<inner-parent-tag}}
    {{$other-arg}}{{/other-arg}}
{{/inner-parent-tag}}

{{:<outer-parent-tag}}
    {{$arg}}{{/arg}}
    {{<inner-parent-tag}}
        {{$other-arg}}{{/other-arg}}
    {{/inner-parent-tag}}
    {{! optionally, let us use the second argument in the outer inline template as well}}
    {{$other-arg}}{{/other-arg}}
{{/outer-parent-tag}}
```

> 
> Note: in this example I had to explicitly mark which inline definitions correspond to closed partials and which correspond to parent tags, because otherwise it would quickly get fairly confusing:
> 
> ```
> {{:outer-parent-tag}}
>   {{$arg}}{{/arg}}
>   {{:ugly-workaround}}
>     # render the argument here
>     {{$other-arg}}{{/other-arg}}
>   {{/ugly-workaround}}
>   {{:inner-parent-tag}}
>     {{>ugly-workaround}}
>   {{/inner-parent-tag]]
>   ... uses {{<inner-parent-tag}} ...
> {{/outer-parent-tag}}
> ```
> 
> The fact that parent-inside-parent is a bit delicate while closed-inside-parent is not suggests that it's good to force people to be explicit about whether they are defining an inline parent or an inline closed partial.

Honestly, despite the fact that the workaround you're describing is convoluted and unnecessary, I do not even find it that confusing.

As I wrote before, I believe that the distinction between partials and parents is purely at the site of interpolation ("in the eyes of the beholder", so to speak), not at the site of definition. Just `{{:name}}` rather than `{{:<name}}` and `{{:>name}}` should be enough, I think.

**Comment by groue** [comment]
(Hi folks. Would you please not quote my username @groue in your comments? I have long stopped working with Mustache, and I wish I would not be notified about threads started ~ 10 years ago. Thank you in advance!)

**Comment by jgonggrijp** [comment]
Hi @groue. Please set the notification settings for this repository to "ignore". In that way, you will never be notified, not even if we mention you. Then you do not need to rely on the cooperation from us and future people who will not have seen your request, and we can continue mentioning you, which has a meaningful function for us because you were a major contributor in the past.

**Comment by groue** [comment]
Did that.

Still, consider that notifying people 10 years after their last message in a thread is something that you should avoid, so that people do not have to make such a radical setup change.

Consider that after I set to notification settings to "ignore", people who _do intend_ to notify me through this repository won't be able to do so. _Your_ actions have a negative effects on _other people_ actions. I'm sure this was not your initial intention.

Your cooperation, as well as cooperation from future people, is something _we all_ rely on, regardless of all the features Github brings in order to cope with notification noise.

Have a nice day!

**Comment by gasche** [comment]
@jgonggrijp your suggestions to have inline definitions scope over the whole file makes sense to me. (For me it makes even more sense to allow them inside sections, and then scope them only to this section.) But we still have to specify how they interact with partials: are they visible from within partials called in the file?

Personally I would expect this to work:

 ```
{{:part1}}...{{/part1}}

{{:part2}}
  ...
  {{>part1}}
  ...
{{/part2}}

{{>part2}}
```

but should that work in the case where `part2` is an external partial, rather than an inline partial?

**Comment by jgonggrijp** [comment]
Before I engage in the discussion again: please forgive my confrontational style. I read back my previous post and realized that it could come across as slightly polemic, but this is not what I'm after. I consider us to be on the same team: we try to arrive at a spec that works well enough for all implementers.

> @jgonggrijp your suggestions to have inline definitions scope over the whole file makes sense to me.

Glad to read that!

> (For me it makes even more sense to allow them inside sections, and then scope them only to this section.)

Honestly, I can see the sense in that as well. I imagine a use case like the following:

```
{{:address}}Doctor {{name}}{{/address}}

Hi {{>address}}!

{{#promotion}}
    {{:address}}Professor {{name}}{{/address}}
    
    Congratulations, {{>address}}!
{{/promotion}}

Goodbye, {{>address}}.
```

With `{name: "Who"}`, I would agree that the following output would be the most sensible (or least surprising):

```
Hi Doctor Who!
    Congratulations, Professor Who!
Goodbye, Doctor Who.
```

However, it is sensibility at a cost: the added complexity of implementation. Also, looking at the example, I wonder: do both inline templates really need to have the same name? Why not name them differently? I think that would even be less ambiguous and easier to understand.

```
{{:addressDoctor}}Doctor {{name}}{{/addressDoctor}}

Hi {{>addressDoctor}}!

{{#promotion}}
    {{:addressProfessor}}Professor {{name}}{{/addressProfessor}}
    
    Congratulations, {{>addressProfessor}}!
{{/promotion}}

Goodbye, {{>addressDoctor}}.
```

Once we agree to name each inline template differently, we no longer need rules about how they might shadow each other. We can also leave the choice to users, whether they want to restrict themselves to using a particular inline template inside a particular scope or not. It becomes a matter of taste rather than a matter of necessity.

> But we still have to specify how they interact with partials: are they visible from within partials called in the file?

Ah, I realize you asked this before and I misunderstood the question. Sorry about that.

> 
> Personally I would expect this to work:
> 
> ```
> {{:part1}}...{{/part1}}
> 
> {{:part2}}
>  ...
>  {{>part1}}
>  ...
> {{/part2}}
> 
> {{>part2}}
> ```

Agreed.

> 
> but should that work in the case where `part2` is an external partial, rather than an inline partial?

I think no: I would expect inline templates to be private to the file where they are defined. Otherwise, it becomes intractable where "external" partials/parents come from. In the following example, the author of `part4.mustache` might make `part2.mustache` render something that the author of `part2.mustache` never intended:

```
{{!part1.mustache}}
The regular thing.

{{!part2.mustache}}
{{>part1}}

{{!part3.mustache (behaves as author of part2.mustache intended)}}
{{>part2}}

{{!part4.mustache ("hijacks" part2.mustache)}}
{{:part1}}
    Now for something completely different.
{{/part1}}
{{>part2}}
```

I would agree that there is a use case for "hackable" templates, but I think it should be opt-in, and blocks already address that need.

```
{{!part1.mustache}}
The regular thing.

{{!part2.mustache}}
{{$hackme}}{{>part1}}{{/hackme}}

{{!part3.mustache (uses part2.mustache without customization)}}
{{>part2}}

{{!part4.mustache (uses part2.mustache with customization)}}
{{:part1}}
    Now for something completely different.
{{/part1}}
{{<part2}}
    {{$hackme}}{{>part1}}{{/hackme}}
{{/part2}}
```

**Comment by jgonggrijp** [comment]
This discussion continues in #162.
