### ISSUE TITLE
Clarification: Interpolation Context Sigil

### ISSUE THREAD

**Issue by KentonWhite** [mustache/spec#74]
I'm looking for clarification about using '.' as the context sigil in [interpolation](https://github.com/mustache/spec/blob/master/specs/interpolation.yml). The spec says

>  1) Split the name on periods; the first part is the name to resolve, any 
>  remaining parts should be retained.
>  ...
>  5) If any name parts were retained in step 1, each should be resolved
>  against a context stack containing only the result from the former
>  resolution.  If any part fails resolution, the result should be considered
>  falsey, and should interpolate as the empty string.

I'm working with a Mustache implementation in the R language. R allows for '.' in variable names. It uses '$' and '@' as context sigils. This puts me in a bind. To be compliant with the Mustache spec, I must split names on periods and then resolve each remaining piece within the previous context. Doing this in R returns empty strings for valid R expressions, e.g. `{{data.frame$foo}}` will return the empty string regardless if `data.frame` exists on the current stack or if the name `foo` is valid in the context of `data.frame` .

Since Mustache is meant to be language agnostic, can I interpret "split the name on periods" to mean "split the name on context sigils"?

**Comment by jgonggrijp** [comment]
I somewhat disagree with the above advice; if an implementation uses `$` instead of `.` as the name separator, then templates targeting that implementation will not be portable to other implementations and vice versa. That said, if portability is not a goal, then `$` might indeed be the best for R.

Closing now as this question no longer seems to looking for an answer.
